# Generated by Django 5.1.3 on 2024-12-01 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Краткое описание новости'),
            preserve_default=False,
        ),
    ]
